### PR TITLE
Add DNI field to customers models and views 

### PR DESCRIPTION
**Pull request by osvaldoalvaradodev**
Add Dni fields to customers models and views

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@osvaldoalvaradodev I'm trying to accept Pull Requests with functions that majority of users would need. In this case, I'm not sure majority of users would need DNI or would name that field exactly like you did. So, sorry, I would be against such a change for everyone.

**Comment by osvaldoalvaradodev** [comment]
Can i change to not required ? but in latin america is required DNI for stay in hotel/hostels/motels.

I dont know how operate this in england for example.

**Comment by PovilasKorop** [comment]
@osvaldoalvaradodev exactly this is a problem - we need to keep the repository applicable for ALL WORLD, that's why I don't want to accept this change at all, it's too narrow for your specific case you want to create. So you may leave that change in your own project, but globally it's a not a fit, sorry.

**Comment by osvaldoalvaradodev** [comment]
No problem, I understand, i want to try to add other features more globally. :D

**Pull request closed without merging**
